# Generated by Django 5.1.4 on 2024-12-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_vocacionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='resultadotest',
            name='area_vocacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_vocacionales.areavocacional'),
        ),
        migrations.AddField(
            model_name='resultadotest',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
